---
- name: PIP dependency management
  hosts: packer
  user: root
  gather_facts: no
  tasks:
    - name: setuptools
      pip:
        name: setuptools
        state: latest
    - name: pycrypto
      pip:
        name: pycrypto
        state: latest
    - name: awscli
      pip:
        name: awscli
        state: latest
