---
- name: Terraform dependency management
  hosts: packer
  user: root
  gather_facts: no
  tasks:
    - name: download
      shell: wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
      args:
        chdir: /root/tmp
    - name: install
      shell: unzip terraform_0.11.11_linux_amd64.zip -d /bin
      args:
        chdir: /root/tmp
